// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sled.proto

/*
Package sled is a generated protocol buffer package.

It is generated from these files:
	sled.proto

It has these top-level messages:
	CommandRequest
	UpdateResponse
	UpdateRequest
	CommandSet
	Wipe
	Write
	Kexec
*/
package sled

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandRequest struct {
	Mac string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
}

func (m *CommandRequest) Reset()                    { *m = CommandRequest{} }
func (m *CommandRequest) String() string            { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()               {}
func (*CommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type UpdateResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateRequest struct {
	Mac        string      `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	CommandSet *CommandSet `protobuf:"bytes,2,opt,name=commandSet" json:"commandSet,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *UpdateRequest) GetCommandSet() *CommandSet {
	if m != nil {
		return m.CommandSet
	}
	return nil
}

type CommandSet struct {
	Wipe  *Wipe  `protobuf:"bytes,1,opt,name=wipe" json:"wipe,omitempty"`
	Write *Write `protobuf:"bytes,2,opt,name=write" json:"write,omitempty"`
	Kexec *Kexec `protobuf:"bytes,3,opt,name=kexec" json:"kexec,omitempty"`
}

func (m *CommandSet) Reset()                    { *m = CommandSet{} }
func (m *CommandSet) String() string            { return proto.CompactTextString(m) }
func (*CommandSet) ProtoMessage()               {}
func (*CommandSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommandSet) GetWipe() *Wipe {
	if m != nil {
		return m.Wipe
	}
	return nil
}

func (m *CommandSet) GetWrite() *Write {
	if m != nil {
		return m.Write
	}
	return nil
}

func (m *CommandSet) GetKexec() *Kexec {
	if m != nil {
		return m.Kexec
	}
	return nil
}

type Wipe struct {
	Device string `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
}

func (m *Wipe) Reset()                    { *m = Wipe{} }
func (m *Wipe) String() string            { return proto.CompactTextString(m) }
func (*Wipe) ProtoMessage()               {}
func (*Wipe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Wipe) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type Write struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Device string `protobuf:"bytes,2,opt,name=device" json:"device,omitempty"`
	Image  []byte `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (m *Write) Reset()                    { *m = Write{} }
func (m *Write) String() string            { return proto.CompactTextString(m) }
func (*Write) ProtoMessage()               {}
func (*Write) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Write) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Write) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Write) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type Kexec struct {
	Kernel string `protobuf:"bytes,1,opt,name=kernel" json:"kernel,omitempty"`
	Append string `protobuf:"bytes,2,opt,name=append" json:"append,omitempty"`
	Initrd string `protobuf:"bytes,3,opt,name=initrd" json:"initrd,omitempty"`
}

func (m *Kexec) Reset()                    { *m = Kexec{} }
func (m *Kexec) String() string            { return proto.CompactTextString(m) }
func (*Kexec) ProtoMessage()               {}
func (*Kexec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Kexec) GetKernel() string {
	if m != nil {
		return m.Kernel
	}
	return ""
}

func (m *Kexec) GetAppend() string {
	if m != nil {
		return m.Append
	}
	return ""
}

func (m *Kexec) GetInitrd() string {
	if m != nil {
		return m.Initrd
	}
	return ""
}

func init() {
	proto.RegisterType((*CommandRequest)(nil), "CommandRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*CommandSet)(nil), "CommandSet")
	proto.RegisterType((*Wipe)(nil), "Wipe")
	proto.RegisterType((*Write)(nil), "Write")
	proto.RegisterType((*Kexec)(nil), "Kexec")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sled service

type SledClient interface {
	Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandSet, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type sledClient struct {
	cc *grpc.ClientConn
}

func NewSledClient(cc *grpc.ClientConn) SledClient {
	return &sledClient{cc}
}

func (c *sledClient) Command(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandSet, error) {
	out := new(CommandSet)
	err := grpc.Invoke(ctx, "/Sled/Command", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sledClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/Sled/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sled service

type SledServer interface {
	Command(context.Context, *CommandRequest) (*CommandSet, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

func RegisterSledServer(s *grpc.Server, srv SledServer) {
	s.RegisterService(&_Sled_serviceDesc, srv)
}

func _Sled_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SledServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Sled/Command",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SledServer).Command(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sled_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SledServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Sled/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SledServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sled_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Sled",
	HandlerType: (*SledServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Command",
			Handler:    _Sled_Command_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Sled_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sled.proto",
}

func init() { proto.RegisterFile("sled.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xd9, 0xd6, 0x76, 0xff, 0xdd, 0xfd, 0xdd, 0xe4, 0x22, 0x52, 0x87, 0x88, 0xe4, 0x45,
	0x45, 0xc8, 0xc3, 0xfc, 0x08, 0xf3, 0x45, 0x04, 0x85, 0x0c, 0x19, 0xf8, 0x56, 0x93, 0x8b, 0x84,
	0xad, 0x6d, 0x6c, 0x3a, 0xe7, 0xc7, 0x97, 0x24, 0xad, 0xb6, 0x0f, 0xbe, 0xe5, 0x77, 0x4e, 0xee,
	0xb9, 0xe1, 0xde, 0x00, 0xd8, 0x1d, 0x29, 0x6e, 0xaa, 0xb2, 0x2e, 0x19, 0x83, 0xd9, 0xaa, 0xcc,
	0xf3, 0xac, 0x50, 0x82, 0x3e, 0xf6, 0x64, 0x6b, 0x3c, 0x86, 0x51, 0x9e, 0xc9, 0x74, 0x70, 0x39,
	0xb8, 0x9e, 0x08, 0x77, 0x64, 0xf7, 0x30, 0x7b, 0x31, 0x2a, 0xab, 0x49, 0x90, 0x35, 0x65, 0x61,
	0x09, 0x53, 0x18, 0xdb, 0xbd, 0x94, 0x64, 0xad, 0xbf, 0xf7, 0x4f, 0xb4, 0xe8, 0x9c, 0x9c, 0xac,
	0xcd, 0xde, 0x29, 0x1d, 0xfa, 0x84, 0x16, 0xd9, 0x13, 0x1c, 0xb5, 0x29, 0x7f, 0x34, 0xc2, 0x5b,
	0x00, 0x19, 0x1e, 0xb3, 0xa6, 0xda, 0xd7, 0x4f, 0x97, 0x53, 0xbe, 0xfa, 0x91, 0x44, 0xc7, 0x66,
	0x12, 0xe0, 0xd7, 0xc1, 0x33, 0x88, 0x0e, 0xda, 0x90, 0x4f, 0x9b, 0x2e, 0x63, 0xbe, 0xd1, 0x86,
	0x84, 0x97, 0xf0, 0x1c, 0xe2, 0x43, 0xa5, 0x6b, 0x6a, 0x02, 0x13, 0xbe, 0x71, 0x24, 0x82, 0xe8,
	0xdc, 0x2d, 0x7d, 0x91, 0x4c, 0x47, 0x8d, 0xfb, 0xe8, 0x48, 0x04, 0x91, 0x5d, 0x40, 0xe4, 0x92,
	0xf0, 0x14, 0x12, 0x45, 0x9f, 0x5a, 0x52, 0xf3, 0xdc, 0x86, 0xd8, 0x03, 0xc4, 0x3e, 0x0d, 0x11,
	0xa2, 0x22, 0xcb, 0x5b, 0xdb, 0x9f, 0x3b, 0x45, 0xc3, 0x6e, 0x11, 0x9e, 0x40, 0xac, 0x73, 0x37,
	0x21, 0xd7, 0xf2, 0xbf, 0x08, 0xc0, 0x9e, 0x21, 0xf6, 0xad, 0x5d, 0xd9, 0x96, 0xaa, 0x82, 0x76,
	0x6d, 0xaf, 0x40, 0x4e, 0xcf, 0x8c, 0xa1, 0x42, 0xb5, 0x71, 0x81, 0x9c, 0xae, 0x0b, 0x5d, 0x57,
	0xca, 0xe7, 0x4d, 0x44, 0x43, 0xcb, 0x57, 0x88, 0xd6, 0x3b, 0x52, 0x78, 0x05, 0xe3, 0x66, 0x50,
	0x38, 0xe7, 0xfd, 0x65, 0x2f, 0xba, 0xd3, 0xc5, 0x1b, 0x48, 0xc2, 0x86, 0x70, 0xc6, 0x7b, 0xab,
	0x5a, 0xcc, 0x79, 0xff, 0x03, 0xbc, 0x25, 0xfe, 0xf7, 0xdc, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x92, 0x95, 0x6f, 0x45, 0x4b, 0x02, 0x00, 0x00,
}
